# Generated by Django 3.0.6 on 2020-05-11 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('col_uuid', models.CharField(blank=True, max_length=31, null=True)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('validated', 'validated'), ('error', 'error'), ('uploaded', 'uploaded')], default='submitted', max_length=15)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
